# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jonathan Cole
author: Jonathan Cole
description: >- # this means to ignore newlines until "baseurl:"
  Jonathan Cole's website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jons.website" # the base hostname & protocol for your site, e.g. http://example.com
avatar: "assets/images/posterized.png"

email: jon@jons.website
resume: /assets/resume.pdf
github_url: https://www.github.com/colejd
linkedin_url: https://www.linkedin.com/in/joncole04412
twitter_username: "@12millionbeans"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # default_lang: swift
    css_class: 'highlight'
    # span:
    #   line_numbers: true
    # block:
    #   line_numbers: true
    #   start_line: 1

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# Format the blog posts with the following (puts generated posts into the /blog subdirectory)
# permalink: /blog/:categories/:year/:month/:day/:title.html

collections:
  pages:
    output: true
    permalink: /:path
  posts:
    output: true
    permalink: /blog/:title/
    

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
  envs:           [local]
  blanklines:       false
  profile:          false
  startings: [html, head, body]

sass:
  style: compressed # expanded

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
