name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Set up NPM
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Restore NPM dependencies from cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install NPM dependencies
        run: npm install

      - name: 🔨 Install Gems and build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.JEKYLL_PAT }}
          publish_dir: ./_site
          publish_branch: gh-pages

      # - name: Build website into gh-pages branch # Also installs gems
      #   uses: helaili/jekyll-action@v2
      #   env:
      #     JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
      #   with:
      #     target_branch: 'gh-pages'
